using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Splines;

public class PoleNetworkBuilder : MonoBehaviour
{
    [Header("자동 연결 설정")]
    [Tooltip("이 거리 안에 있는 전봇대만 연결 후보로 봅니다.")]
    public float maxConnectDistance = 30f;

    [Tooltip("방향별 후보로 인정할 각도 기준입니다. 값이 높을수록 정면에 가까운 노드만 선택합니다.")]
    [Range(0f, 1f)]
    public float directionDotThreshold = 0.45f;

    [Tooltip("한 전봇대에서 앞/뒤/좌/우 방향별로 최대 하나씩 연결합니다.")]
    public bool useFourDirectionLimit = true;

    [Header("자동 생성 오브젝트")]
    public string generatedWireParentName = "AutoGeneratedWires";

    [Tooltip("자동 생성 전에 기존 자동 생성 전선을 삭제합니다.")]
    public bool clearOldGeneratedWires = true;

    [Header("전선 자동 생성")]
    [Tooltip("전선 중간 지점을 아래로 내리는 정도입니다. 0이면 직선입니다.")]
    public float wireSagAmount = 0.4f;

    [Tooltip("전선을 몇 개의 점으로 그릴지 정합니다.")]
    [Range(2, 64)]
    public int wireVisualPointCount = 16;

    [Tooltip("전선 두께입니다.")]
    public float wireWidth = 0.06f;

    [Tooltip("전선 색상입니다.")]
    public Color wireColor = new Color(0.05f, 0.05f, 0.05f, 1f);

    [Tooltip("전선 Line Renderer에 사용할 머티리얼입니다. 비워도 기본 머티리얼을 자동으로 찾습니다.")]
    public Material wireMaterial;

    [Tooltip("전봇대 위치가 바뀌면 전선도 자동으로 따라가게 합니다.")]
    public bool updateWireEveryFrame = true;

    [Header("선 꼬임 방지")]
    [Tooltip("새 전선이 기존 전선과 XZ 평면에서 교차하면 생성하지 않습니다.")]
    public bool preventCrossing = true;

    [Header("디버그")]
    public bool showDebugLog = true;
    public bool drawGizmos = true;

    private readonly List<ConnectionPair> createdPairs = new List<ConnectionPair>();

    [ContextMenu("Build Pole Network")]
    public void BuildPoleNetwork()
    {
        PoleNode[] nodes = FindObjectsByType<PoleNode>(FindObjectsSortMode.None);

        if (nodes == null || nodes.Length == 0)
        {
            Debug.LogWarning("PoleNode를 찾지 못했습니다.");
            return;
        }

        if (showDebugLog)
        {
            Debug.Log("자동 연결 시작 / PoleNode 개수: " + nodes.Length);
        }

        createdPairs.Clear();

        ClearAllNodeConnections(nodes);

        Transform wireParent = PrepareGeneratedWireParent();

        foreach (PoleNode node in nodes)
        {
            if (node == null)
            {
                continue;
            }

            List<PoleNode> selectedTargets = SelectTargetNodesByDirection(node, nodes);

            foreach (PoleNode target in selectedTargets)
            {
                if (target == null)
                {
                    continue;
                }

                if (IsPairAlreadyCreated(node, target))
                {
                    continue;
                }

                if (preventCrossing && DoesNewConnectionCrossExisting(node, target))
                {
                    if (showDebugLog)
                    {
                        Debug.Log("선 교차로 연결 제외: " + node.name + " - " + target.name);
                    }

                    continue;
                }

                SplineContainer newWire = CreateAutoWire(node, target, wireParent);

                if (newWire == null)
                {
                    continue;
                }

                node.AddConnection(target, newWire, false);
                target.AddConnection(node, newWire, true);

                createdPairs.Add(new ConnectionPair(node, target, newWire));

                if (showDebugLog)
                {
                    Debug.Log("자동 연결 생성: " + node.name + " <-> " + target.name);
                }
            }
        }

        if (showDebugLog)
        {
            Debug.Log("자동 연결 완료 / 생성된 전선 수: " + createdPairs.Count);
        }
    }

    private void ClearAllNodeConnections(PoleNode[] nodes)
    {
        foreach (PoleNode node in nodes)
        {
            if (node == null)
            {
                continue;
            }

            node.ClearConnections();
        }
    }

    private Transform PrepareGeneratedWireParent()
    {
        GameObject parentObject = GameObject.Find(generatedWireParentName);

        if (parentObject == null)
        {
            parentObject = new GameObject(generatedWireParentName);
        }

        if (clearOldGeneratedWires)
        {
            List<GameObject> childrenToDelete = new List<GameObject>();

            for (int i = 0; i < parentObject.transform.childCount; i++)
            {
                childrenToDelete.Add(parentObject.transform.GetChild(i).gameObject);
            }

            foreach (GameObject child in childrenToDelete)
            {
                if (Application.isPlaying)
                {
                    Destroy(child);
                }
                else
                {
                    DestroyImmediate(child);
                }
            }
        }

        return parentObject.transform;
    }

    private List<PoleNode> SelectTargetNodesByDirection(PoleNode origin, PoleNode[] allNodes)
    {
        List<PoleNode> result = new List<PoleNode>();

        if (!useFourDirectionLimit)
        {
            foreach (PoleNode candidate in allNodes)
            {
                if (candidate == null || candidate == origin)
                {
                    continue;
                }

                float distance = Vector3.Distance(origin.Position, candidate.Position);

                if (distance <= maxConnectDistance)
                {
                    result.Add(candidate);
                }
            }

            return result;
        }

        PoleNode bestForward = null;
        PoleNode bestBack = null;
        PoleNode bestRight = null;
        PoleNode bestLeft = null;

        float bestForwardScore = float.MinValue;
        float bestBackScore = float.MinValue;
        float bestRightScore = float.MinValue;
        float bestLeftScore = float.MinValue;

        Vector3 worldForward = Vector3.forward;
        Vector3 worldBack = Vector3.back;
        Vector3 worldRight = Vector3.right;
        Vector3 worldLeft = Vector3.left;

        foreach (PoleNode candidate in allNodes)
        {
            if (candidate == null || candidate == origin)
            {
                continue;
            }

            Vector3 toCandidate = candidate.Position - origin.Position;
            toCandidate.y = 0f;

            float distance = toCandidate.magnitude;

            if (distance <= 0.001f)
            {
                continue;
            }

            if (distance > maxConnectDistance)
            {
                continue;
            }

            Vector3 direction = toCandidate.normalized;

            TrySetBestCandidate(direction, worldForward, distance, candidate, ref bestForward, ref bestForwardScore);
            TrySetBestCandidate(direction, worldBack, distance, candidate, ref bestBack, ref bestBackScore);
            TrySetBestCandidate(direction, worldRight, distance, candidate, ref bestRight, ref bestRightScore);
            TrySetBestCandidate(direction, worldLeft, distance, candidate, ref bestLeft, ref bestLeftScore);
        }

        AddIfNotNullAndUnique(result, bestForward);
        AddIfNotNullAndUnique(result, bestBack);
        AddIfNotNullAndUnique(result, bestRight);
        AddIfNotNullAndUnique(result, bestLeft);

        return result;
    }

    private void TrySetBestCandidate(
        Vector3 candidateDirection,
        Vector3 baseDirection,
        float distance,
        PoleNode candidate,
        ref PoleNode bestNode,
        ref float bestScore
    )
    {
        float dot = Vector3.Dot(candidateDirection, baseDirection);

        if (dot < directionDotThreshold)
        {
            return;
        }

        float score = dot * 10f - distance * 0.1f;

        if (score > bestScore)
        {
            bestScore = score;
            bestNode = candidate;
        }
    }

    private void AddIfNotNullAndUnique(List<PoleNode> list, PoleNode node)
    {
        if (node == null)
        {
            return;
        }

        if (list.Contains(node))
        {
            return;
        }

        list.Add(node);
    }

    private bool IsPairAlreadyCreated(PoleNode a, PoleNode b)
    {
        foreach (ConnectionPair pair in createdPairs)
        {
            if (pair == null)
            {
                continue;
            }

            if ((pair.nodeA == a && pair.nodeB == b) || (pair.nodeA == b && pair.nodeB == a))
            {
                return true;
            }
        }

        return false;
    }

    private SplineContainer CreateAutoWire(PoleNode startNode, PoleNode endNode, Transform parent)
    {
        string wireName = "WireSpline_" + startNode.name + "_" + endNode.name;

        GameObject wireObject = new GameObject(wireName);
        wireObject.transform.SetParent(parent);
        wireObject.transform.position = Vector3.zero;
        wireObject.transform.rotation = Quaternion.identity;
        wireObject.transform.localScale = Vector3.one;

        SplineContainer splineContainer = wireObject.AddComponent<SplineContainer>();
        wireObject.AddComponent<LineRenderer>();

        AutoWireSegment autoWireSegment = wireObject.AddComponent<AutoWireSegment>();
        autoWireSegment.updateEveryFrame = updateWireEveryFrame;

        autoWireSegment.Initialize(
            startNode,
            endNode,
            wireSagAmount,
            wireVisualPointCount,
            wireWidth,
            wireColor,
            wireMaterial
        );

        return splineContainer;
    }

    private bool DoesNewConnectionCrossExisting(PoleNode newA, PoleNode newB)
    {
        Vector2 a = ToXZ(newA.Position);
        Vector2 b = ToXZ(newB.Position);

        foreach (ConnectionPair pair in createdPairs)
        {
            if (pair == null)
            {
                continue;
            }

            if (pair.nodeA == null || pair.nodeB == null)
            {
                continue;
            }

            if (pair.nodeA == newA || pair.nodeA == newB || pair.nodeB == newA || pair.nodeB == newB)
            {
                continue;
            }

            Vector2 c = ToXZ(pair.nodeA.Position);
            Vector2 d = ToXZ(pair.nodeB.Position);

            if (DoLineSegmentsIntersect(a, b, c, d))
            {
                return true;
            }
        }

        return false;
    }

    private Vector2 ToXZ(Vector3 position)
    {
        return new Vector2(position.x, position.z);
    }

    private bool DoLineSegmentsIntersect(Vector2 a, Vector2 b, Vector2 c, Vector2 d)
    {
        float direction1 = Cross(d - c, a - c);
        float direction2 = Cross(d - c, b - c);
        float direction3 = Cross(b - a, c - a);
        float direction4 = Cross(b - a, d - a);

        if (((direction1 > 0f && direction2 < 0f) || (direction1 < 0f && direction2 > 0f)) &&
            ((direction3 > 0f && direction4 < 0f) || (direction3 < 0f && direction4 > 0f)))
        {
            return true;
        }

        return false;
    }

    private float Cross(Vector2 a, Vector2 b)
    {
        return a.x * b.y - a.y * b.x;
    }

    private void OnDrawGizmos()
    {
        if (!drawGizmos)
        {
            return;
        }

        PoleNode[] nodes = FindObjectsByType<PoleNode>(FindObjectsSortMode.None);

        if (nodes == null)
        {
            return;
        }

        Gizmos.color = Color.yellow;

        foreach (PoleNode node in nodes)
        {
            if (node == null)
            {
                continue;
            }

            Gizmos.DrawSphere(node.Position, 0.25f);
        }
    }

    private class ConnectionPair
    {
        public PoleNode nodeA;
        public PoleNode nodeB;
        public SplineContainer wireSpline;

        public ConnectionPair(PoleNode nodeA, PoleNode nodeB, SplineContainer wireSpline)
        {
            this.nodeA = nodeA;
            this.nodeB = nodeB;
            this.wireSpline = wireSpline;
        }
    }
}